Importing packages 

```{r}
library(tidyverse)
library(here)
library(dotenv)
library(readr)
library(rlang)
library(glue)

load_dot_env(file=here(".env"))
SERVER_PATH = Sys.getenv("SERVER_PATH")
PROJECT_VERSION = Sys.getenv("PROJECT_VERSION")
```

```{r constants}
RAW_DATA_PATH = file.path(SERVER_PATH, "data", "raw", "lookit")

CDI2A_TEMPLATE <- "https://qualtricsxmhcv2m8q6d.qualtrics.com/jfe/form/SV_7NAZ6riQu1aBIZU?ChildID="
CDI1_TEMPLATE  <- "https://ucsd.co1.qualtrics.com/jfe/form/SV_3UTxIUSEYbe3QdE?ChildID="

SAMPLE1_STUDY_NAME <- "How do children think about categories?"
SAMPLE2_STUDY_NAME <- "Can you find the rose?"

gift_cards <- read.csv(file.path(RAW_DATA_PATH, "gift_cards.csv"), stringsAsFactors = FALSE)

# Read the combined subjects data CSV (has a 'section' column for sample1/sample2)
subjects_data_all <- read.csv(file.path(RAW_DATA_PATH, "subject_data.csv"), stringsAsFactors = FALSE)
# Filter to the relevant section if PROJECT_VERSION specifies one
VALID_SECTIONS <- c("sample1", "sample2")
subjects_data <- if (PROJECT_VERSION %in% VALID_SECTIONS) {
  subjects_data_all |> dplyr::filter(section == PROJECT_VERSION)
} else {
  subjects_data_all
}
cdi_level1data <- read.csv(file.path(RAW_DATA_PATH, "cdi", "cdi_level1.csv"))
cdi_level2adata <- read.csv(file.path(RAW_DATA_PATH, "cdi", "cdi_level2a.csv"))
existing_cdi_child_ids <- unique(c(as.character(cdi_level1data$ChildID),
                                   as.character(cdi_level2adata$ChildID)))
```

```{r}
hashed_gift_card_text = "As promised, here is the Amazon.com gift card code for participating:
 
  [gift_card]
 
 To use this code, please go to: https://www.amazon.com/gc/redeem/"

url_gift_card_text = "As promised, here [gift_card] is the link to the Amazon.com gift card for participating."
```

```{r}
email_template = 
  "Dear [parent_name],

Thank you to [child_name] for participating in '[study_name]' on Children Helping Science, run by Bria Long in the Visual Learning Lab at the University of California, San Diego! [survey_text]

[gift_card_text]

If you have any questions or concerns about your child's participation in this study, please email us at vislearnlab@ucsd.edu

Thank you,
Tarun Sepuri
Lab Manager
Visual Learning Lab, University of California, San Diego
https://childrenhelpingscience.com/exp/labs/331/

Please do not reply to this message. If you have questions, please email us at vislearnlab@ucsd.edu" 


survey_template = 
  "As a part of this study, we also ask that parents fill out a vocabulary survey. We are curious how the words that your child knows and does not know affects how they think about categories. Here is a link to the survey: [survey_link]"
```

```{r}
survey_text <- function(section, child_id, child_age) {
  child_age_in_months = child_age / 30;
  if (section != "sample2" || child_id %in% existing_cdi_child_ids) {
    return("")
  } else {
    if (child_age_in_months <= 18) {
      survey_link <- (paste0(CDI1_TEMPLATE, child_id))
    } else {
      survey_link <- (paste0(CDI2A_TEMPLATE, child_id))
    }
    return(survey_template |> str_replace_all("\\[survey_link\\]", survey_link))
  }
}
```

```{r}
fill_email <- function(parent_name, child_name, global_id, age, gift_card, section) {
  gift_card_text <- ifelse(grepl(".com", gift_card), url_gift_card_text, hashed_gift_card_text)
  study_name <- ifelse(section == "sample2", SAMPLE2_STUDY_NAME, SAMPLE1_STUDY_NAME)
  survey_text <- survey_text(section, global_id, age)
  full_email_template <- email_template |>
   str_replace_all("\\[gift_card_text\\]", gift_card_text)
  email_filled <- full_email_template |>
    str_replace_all("\\[parent_name\\]", parent_name) |>
    str_replace_all("\\[child_name\\]", child_name) |>
    str_replace_all("\\[gift_card\\]", gift_card) |>
    str_replace_all("\\[survey_text\\]", survey_text) |>
    str_replace_all("\\[study_name\\]", study_name)
  return(email_filled)
}
```

```{r}
# Filter for unused gift cards
unused_gift_cards <- gift_cards %>%
  filter(used == "")

# Filter for parents who haven't been paid
unpaid_parents <- subjects_data %>%
  filter(Paid == "" | is.na(Paid))

# Match unused gift cards to unpaid parents
matched_data <- unpaid_parents %>%
  mutate(claim_code = unused_gift_cards$claim_code[seq_len(n())]) %>%
# Remove any NA values in case there are more unpaid parents than unused gift cards 
  filter(!is.na(claim_code))

# Apply the function to each row and store the output
output_emails <- mapply(fill_email, matched_data$parent_nickname, matched_data$name, matched_data$global_id, matched_data$age_rounded, matched_data$claim_code, matched_data$section)

# Write to a text file with each output on a new line
writeLines(output_emails, file.path(RAW_DATA_PATH, "matched_gift_cards.txt"), sep = "\n\n")

# Print confirmation
cat("Text file 'matched_gift_cards.txt' has been generated successfully!\n")
```