---
title: "CDI data"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(dplyr)
library(dotenv)
library(here)
library(tibble)

env_file = here(".env")
load_dot_env(file = env_file)
```

```{r}
SERVER_PATH <- Sys.getenv("SERVER_PATH")
```

```{r}
cdi_level1 <- read.csv(file.path(SERVER_PATH, "data/raw/lookit/cdi/cdi_level1.csv"))
cdi_level2a <- read.csv(file.path(SERVER_PATH, "data/raw/lookit/cdi/cdi_level2a.csv"))
subject_data <- read.csv(file.path(SERVER_PATH, "data/raw/lookit/subject_data.csv"))
words_row <- cdi_level1[1,]
#delete unnecessary columns
cdi1_cleaned_rows <- cdi_level1 |>
  # removing participants who did not finish and removing test participants
  slice(-(1:11)) |> filter(Finished == 1) |>
  # only select first instance of participation
  group_by(ChildID) |>
  arrange(StartDate) |>
  slice(1) |> 
  ungroup() |> 
rename(duration_in_seconds = Duration..in.seconds.) 
cdi1_cleaned <- cdi1_cleaned_rows |> select(ChildID, starts_with("Q"))

cdi2a_cleaned_rows <- cdi_level2a |> slice(-(1:8)) |> filter(Finished == 1)  |> rename(duration_in_seconds = Duration..in.seconds.) |>
    # only select first instance of participation
  group_by(ChildID) |>
  arrange(StartDate) |>
  slice(1) |> 
  ungroup() 
cdi2a_cleaned <- cdi2a_cleaned_rows |> select(ChildID, starts_with("Q"))
```

```{r}
# It seems like in cdi2a, we should exlcude rows where Q3 > 1 becayse it is impossible for children to often combine words if they can't say any words
cdi2a_cleaned <- cdi2a_cleaned |> filter(Q1 != "" | Q2 != "" | Q3 == 1)
```

```{r}
#get a mapping table
words <- words_row |> select(starts_with("Q")) |> pivot_longer(cols = starts_with("Q")) |> separate(value, into=c('word_type', 'word'), sep='-') |> mutate(word_type = trimws(word_type), word = trimws(word))
```

```{r}
# transform to pivot long for df1
cdi1_long <- cdi1_cleaned |> pivot_longer(cols=!ChildID, names_to = "question", values_to = 'value') |> mutate(value = trimws(value), value = na_if(value, ""), value = as.numeric(value)) |> 
  rename(child_id = ChildID) |>
  #add survey type and value
  mutate(survey_type = 1,
         responded = ifelse(is.na(value), 0, 1)) 
```

```{r}
#check before merge words to df1_long
setdiff(cdi1_long$question, words$name)

#map into condition
ability <- tibble::tibble(value = c(NA, 1, 2), type = c(NA, 'understands', 'produces'))

#merge conditions and words
cdi1_merged <- cdi1_long %>% left_join(words, c('question' = 'name')) |> left_join(ability, 'value') 

# if type = produces; add type = understands row with value = 1
# if type = understands; add type = produces row with value = 0
# if type = NA ; update type = produces row with value = 0 AND type = understands row with value = 0
# maybe use fill function in R?
```

```{r}
cdi1_complete <- cdi1_merged |>
  # ensure every word has both an "understands" and a "produces" row
  complete(
    nesting(question, child_id, word, word_type, survey_type),
    type = c("understands", "produces")
  ) |>
  # Remove previous rows that had completely unanswered questions
  filter(!is.na(type)) |>
  # treat missing responses as 0 (not responded)
  mutate(
    responded = case_when(
      is.na(value) ~ 0,
      TRUE ~ 1
    )
  ) |>
  # within each child-word combination
  group_by(question, child_id, word) |>
  mutate(
  produced = any(type == "produces" & responded == 1),
  # producting a word implies understanding it
  value = if_else(
    type == "understands" & produced,
    2,
    value
  ),

  responded = if_else(
    type == "understands" & produced,
    1,
    responded
  )
  ) |>
  select(-produced) |>
  ungroup()
```

```{r}
stopifnot(
  cdi1_complete |>
    count(child_id) |>
    pull(n) |>
    n_distinct() == 1
)
```

```{r}
#process df2 similar to df1
cdi2a_long <- cdi2a_cleaned |> 
  pivot_longer(c(Q1, Q2), names_to = 'question_group', values_to = 'label_code') |>
  separate_rows(label_code, sep=',') |> 
  mutate(
    label_code = trimws(label_code), 
    label_code = na_if(label_code, ""), 
    label_code = as.numeric(label_code), 
    value = 1L
    ) |>
  select("ChildID", "question_group", "label_code", "value") |> rename(child_id = ChildID)
```

```{r}
# make a mapping table
# TODO: make CSV instead
words2a <- tibble::tribble(
  ~question_group, ~label_code, ~response_label,
  "Q1", 1, "sock",
  "Q1", 103, "bathtub",
  "Q1", 126, "shower",
  "Q1", 127, "balloon",
  "Q1", 128, "dresser",
  "Q1", 129, "kite",
  "Q1", 130, "camel",
  "Q1", 131, "elephant",
  "Q1", 132, "ladybug",
  "Q1", 133, "cloud",
  "Q1", 134, "tree",
  "Q1", 135, "zipper",
  "Q1", 136, "crow",
  "Q1", 137, "penguin",
  "Q1", 138, "seahorse",
  "Q1", 139, "duck",
  "Q1", 140, "chicken",
  "Q1", 141, "butterfly",
  "Q1", 142, "lizard",
  "Q1", 143, "walrus",
  "Q1", 144, "snake",
  "Q1", 145, "truck",
  "Q1", 146, "car",
  "Q1", 147, "airplane",

  "Q2", 1, "baa baa",
  "Q2", 2, "meow",
  "Q2", 3, "ouch",
  "Q2", 4, "uh oh",
  "Q2", 5, "woof woof",
  "Q2", 6, "bear",
  "Q2", 7, "bird",
  "Q2", 8, "cat",
  "Q2", 9, "dog",
  "Q2", 10, "duck",
  "Q2", 11, "horse",
  "Q2", 12, "airplane",
  "Q2", 13, "boat",
  "Q2", 14, "car",
  "Q2", 15, "ball",
  "Q2", 16, "book",
  "Q2", 17, "game",
  "Q2", 18, "applesauce",
  "Q2", 19, "candy",
  "Q2", 20, "coke",
  "Q2", 21, "cracker",
  "Q2", 22, "juice",
  "Q2", 23, "meat",
  "Q2", 24, "milk",
  "Q2", 25, "peas",
  "Q2", 26, "hat",
  "Q2", 27, "necklace",
  "Q2", 28, "shoe",
  "Q2", 29, "sock",
  "Q2", 30, "chin",
  "Q2", 31, "ear",
  "Q2", 32, "hand",
  "Q2", 33, "leg",
  "Q2", 34, "broom",
  "Q2", 35, "comb",
  "Q2", 36, "mop",
  "Q2", 37, "plate",
  "Q2", 38, "trash",
  "Q2", 39, "tray",
  "Q2", 40, "towel",
  "Q2", 41, "bed",
  "Q2", 42, "bedroom",
  "Q2", 43, "bench",
  "Q2", 44, "oven",
  "Q2", 45, "stairs",
  "Q2", 46, "flag",
  "Q2", 47, "rain",
  "Q2", 48, "star",
  "Q2", 49, "swing",
  "Q2", 50, "school",
  "Q2", 51, "sky",
  "Q2", 52, "party",
  "Q2", 53, "friend",
  "Q2", 54, "mommy",
  "Q2", 55, "person",
  "Q2", 56, "bye",
  "Q2", 57, "hi",
  "Q2", 58, "no",
  "Q2", 59, "shopping",
  "Q2", 60, "thank you",
  "Q2", 61, "carry",
  "Q2", 62, "chase",
  "Q2", 63, "dump",
  "Q2", 64, "finish",
  "Q2", 65, "fit",
  "Q2", 66, "hug",
  "Q2", 67, "listen",
  "Q2", 68, "like",
  "Q2", 69, "pretend",
  "Q2", 70, "rip",
  "Q2", 71, "shake",
  "Q2", 72, "taste",
  "Q2", 73, "gentle",
  "Q2", 74, "think",
  "Q2", 75, "wish",
  "Q2", 76, "all gone",
  "Q2", 77, "cold",
  "Q2", 78, "fast",
  "Q2", 79, "happy",
  "Q2", 80, "hot",
  "Q2", 81, "last",
  "Q2", 82, "tiny",
  "Q2", 83, "wet",
  "Q2", 84, "after",
  "Q2", 85, "day",
  "Q2", 86, "tonight",
  "Q2", 87, "our",
  "Q2", 88, "them",
  "Q2", 89, "this",
  "Q2", 90, "us",
  "Q2", 91, "where",
  "Q2", 92, "beside",
  "Q2", 93, "down",
  "Q2", 94, "under",
  "Q2", 95, "all",
  "Q2", 96, "much",
  "Q2", 97, "could",
  "Q2", 98, "need",
  "Q2", 99, "would",
  "Q2", 100, "if",
)
```

```{r}
# Let df2 contain both selected and non-selected entries
cdi2a_all <- cdi2a_long |> distinct(child_id) |> crossing(words2a)

# Make complete cdi2a dataframe
cdi2a_complete <- cdi2a_all |> left_join(cdi2a_long, by=c('child_id', 'question_group', 'label_code')) |>
  mutate(value = coalesce(value, NA)) |> distinct()
```

```{r}
# add Q3
Q3_mapping <- tibble::tribble(
  ~question_group, ~value, ~response_label,
  'Q3', 1, "Not Yet",
  'Q3', 2, "Sometimes",
  'Q3', 3, "Often"
)

cdi2a_Q3 <- cdi2a_cleaned |>
  select(ChildID, Q3) |> 
  pivot_longer(Q3, names_to = 'question_group', values_to = 'value') |>
  mutate("value" = as.numeric(value)) |>
  left_join(Q3_mapping, by=c('question_group', 'value')) |>
  rename(child_id = ChildID)
  
cdi2a_complete <- bind_rows(cdi2a_complete, cdi2a_Q3)

#add survey type, word type, and value column
cdi2a_complete$survey_type = '2A'

cdi2a_complete <- cdi2a_complete |>
  mutate(responded = ifelse(is.na(value), 0, 1),
         word_type = case_when(
           question_group == "Q1" ~ "extra_words",
           question_group == "Q2" ~ "cdi_words",
           question_group == "Q3" ~ "combine"
         ))
```

```{r}
stopifnot(
  cdi2a_complete |>
    count(child_id) |>
    pull(n) |>
    n_distinct() == 1
)
```

TODO: add in subject data to get age and subject id

```{r}
# Load subject data
subject_data <- read.csv(file.path(SERVER_PATH, "data/raw/lookit/subject_data.csv"))
```

TODO: load in csv files for 1 and 2a 'production' and calculate percentile score for each child based on 'cdi_words' only and not 'extra_words'

```{r}
cdi1_processed <- cdi1_complete |> select(-question) |> left_join(cdi1_cleaned_rows |> select(ChildID, duration_in_seconds, StartDate), by=c("child_id"="ChildID"))

cdi2a_processed <- cdi2a_complete |> select(-question_group, -label_code) |> rename(word = response_label) |> left_join(cdi2a_cleaned_rows |>              select(ChildID, duration_in_seconds, StartDate), by=c("child_id"="ChildID")) |> mutate(type = ifelse(word_type == "combine", word_type, "produces"))

all_cdi_data <- cdi1_processed |> rbind(cdi2a_processed)

cdi_with_subject_data <- all_cdi_data |> left_join(subject_data |> filter(Comments != "Already participated") |> select(local_id, age_rounded, gender, date_created, global_id), by=c("child_id"="global_id")) |> select(-child_id)
```


```{r}
write.csv(cdi_with_subject_data, here("data/main/data_to_analyze/level-participant_source-cdi_data.csv"))
```
