```{r message=FALSE}
library(tidyverse)
library(here)
library(lmerTest)
library(MuMIn)
library(lme4)
library(dotenv)
library(broom)

load_dot_env(file=here(".env"))
PROJECT_VERSION = Sys.getenv("PROJECT_VERSION")
```

### Load data
```{r}
trial_metadata <- read.csv(here("data","metadata","level-trialtype_data.csv"))
trial_summary_data <- read.csv(here("data",PROJECT_VERSION, "processed_data","level-trials_data.csv"))

usable_trials <- looking_data_summarized |>
  filter(exclude_participant_insufficient_data == 0 & trial_exclusion == 0 & exclude_participant == 0) 

# Merging with similarity information and mean-centering main effects
trials_with_effect_vars <- usable_trials |>
  left_join(trial_metadata) |>
  mutate(age_in_months = SubjectInfo.testAge/30)
```

### Run mixed-effects model
```{r message=FALSE}
prereg_main_effect <- lmer(scale(corrected_target_looking) ~ scale(text_similarity)*scale(age_in_months)
                    + (scale(text_similarity) | SubjectInfo.subjID) 
                    + (1|Trials.targetImage) 
                    + (1|Trials.imagePair), 
                    data = trials_with_effect_vars)

main_effect <- lmer(scale(corrected_target_looking) ~ scale(text_similarity)*scale(age_in_months)
                    + scale(AoA_Est_target)
                    + scale(image_similarity)
                    + scale(MeanSaliencyDiff)
                    + (scale(text_similarity) | SubjectInfo.subjID) 
                    + (1|Trials.targetImage) 
                    + (1|Trials.imagePair), 
                    data = trials_with_effect_vars)

age_effect <- lmer(scale(corrected_target_looking) ~ scale(age_in_months) 
                    + (1|Trials.targetImage) 
                    + (1|Trials.imagePair), 
                    data = trials_with_effect_vars)

#summary(main_effect)
anova(main_effect)
r.squaredGLMM(main_effect)

#main_effect_lm <- lm(scale(corrected_target_looking_short) ~ scale(text_similarity), data= trials_with_effect_vars)
```

### Alternate window analyses
```{r}
baseline_covariate_looking <- lmer(scale(mean_target_looking_critical_window) ~ scale(age_in_months)*scale(text_similarity)
                    + scale(AoA_Est_target)
                    + scale(MeanSaliencyDiff)
                    + scale(mean_target_looking_baseline_window)
                    + (1 | SubjectInfo.subjID) 
                    + (1|Trials.targetImage) 
                    + (1|Trials.imagePair), 
                    data = trials_with_effect_vars)

summary(baseline_covariate_looking)
```

```{r}
# table_data <- tidy(main_effect, effects = "fixed") %>%
#   mutate(
#     p.value = 2 * (1 - pnorm(abs(statistic))),  # Calculate p-values for lmer
#     p.value = ifelse(p.value < .001, "< .001", sprintf("%.3f", p.value)),
#     term = case_when(
#       term == "(Intercept)" ~ "Intercept",
#       term == "scale(test_age_centered)" ~ "Age (scaled)",
#       term == "scale(total_num_errors)" ~ "Number of errors (scaled)",
#       TRUE ~ term
#     )
#   ) %>%
#   rename(
#     Predictor = term,
#     "b" = estimate,
#     "SE" = std.error,
#     "t" = statistic,  # Note: changed from z to t for lmer
#     "p" = p.value
#   ) %>%
#   mutate(across(c("b", "SE", "t"), ~round(., 2)))
```